name: 'Load Xcode version'
description: 'Load Xcode version from shared storage and optionally select it'
branding:
  icon: 'at-sign'
  color: 'blue'
inputs:
  xcode_version_location:
    description: 'Location of file where Xcode version is located'
    required: true
    default: '.github/xcode-version'
  autoselect_xcode: 
    description: 'Call `xcode-select` after loading Xcode version'
    required: true
    default: 'true'
outputs:
  xcode_version:
    description: 'Version of Xcode loaded from given location'
runs:
  using: 'node12'
  main: 'index.js'